MONGO:
  HOST: 'localhost'
  PORT: 27017
  DATABASE: 'admin'
  AUTH:
    ENABLED: true
    USERNAME: 'admin'
    PASSWORD: 'password'
    AUTH-DATABASE: 'admin'
REDIS:
  HOST: 127.0.0.1
  PORT: 6379
  AUTHENTICATION:
    ENABLED: false
    PASSWORD: ''
SERVER: "hub"
MESSAGE-REPLY-BOOLEAN: false