MONGO:
  HOST: 127.0.0.1
  PORT: 27017
  DATABASE: 'practice'
  AUTHENTICATION:
    ENABLED: true
    USERNAME: root
    PASSWORD: ''
    DATABASE: 'admin'
REDIS:
  HOST: 127.0.0.1
  PORT: 6379
  AUTHENTICATION:
    ENABLED: false
    PASSWORD: ''
SERVER: "hub"
MESSAGE_REPLY_BOOLEAN: false
ONLINE_DONATORS: true
NAMETAGS: true